### ISSUE TITLE
Execute "podman container runlabel install imageID" run into errors

### ISSUE THREAD

**Issue by GraceWang571** [fcrozat/gdm-container#1]
1. On TW, install podman and accountsservice packages
2. run as root: podman container runlabel install registry.opensuse.org/home/fcrozat/branches/opensuse/templates/images/tumbleweed/containers/gdm-container

Actual Result:
We got `cp: cannot stat '/container/usr/lib/tmpfiles.d/gdm.conf': No such file or directory` error.

**Comment by fcrozat** [comment]
Fixed with f234fd32213c8847b161f3444cc770b637ea3331
