### ISSUE TITLE
Fail to run gdm

### ISSUE THREAD

**Issue by GraceWang571** [fcrozat/gdm-container#2]
Steps:
1. Deploy the container (follow the steps in README)
2. Try to run gdm with ` systemctl start gdm` OR `podman container runlabel run registry.opensuse.org/home/fcrozat/branches/opensuse/templates/images/tumbleweed/containers/gdm-container`

Actual Result:
Fail to start gdm. And we can find the below erros:
Jul 14 10:06:04 192.168.122.42 gdm[8442]: Gdm: Can’t find the GDM user “gdm”. Aborting!
Jul 14 10:06:04 192.168.122.42 gdm[8442]: Gdm: The GDM user should not be root. Aborting!
Jul 14 10:06:04 192.168.122.42 gdm[8442]: Gdm: Can’t find the GDM group “gdm”. Aborting!
Jul 14 10:06:04 192.168.122.42 gdm[8442]: Gdm: The GDM group should not be root. Aborting!
Jul 14 10:06:04 192.168.122.42 gdm[8442]: Gdm: GdmManager: couldn't look up username gdm
Jul 14 10:06:04 192.168.122.42 gdm[8442]: Gdm: GdmDisplay: Session never registered, failing

**Comment by yifanjiang** [comment]
Checked with the reporter, it seems systemd-userdbd service  is required to make the drop-in "gdm" user worked.

**Comment by fcrozat** [comment]
Fixed in a61f16af77f38edb6b8e8675ee1996944adb0187
