### ISSUE TITLE
Avoid duplicate uid/gid of gdm user

### ISSUE THREAD

**Issue by yifanjiang** [fcrozat/gdm-container#3]
The gdm user is set to a fixed user and group id pair as 473:473. My testing system somehow randomly make dnsmasq using this pair of uid/gid:

```
user@localhost:~> getent group | grep 473
dnsmasq:x:473:
gdm:x:473:
user@localhost:~> getent passwd | grep 473
dnsmasq:x:473:473:dnsmasq:/var/lib/empty:/usr/sbin/nologin
gdm:x:473:473:Gnome Display Manager daemon:/var/lib/gdm:/usr/sbin/nologin
```

We may find a way to mitigate the impact.

**Comment by fcrozat** [comment]
This is due to entries created in /etc/userdb which I hardcoded based on my system :(

I could change those files to create the symlink when the label "install" is run (and check an available UID/GID) but it won't prevent this UID/GID to be used by another package if installed later..
